### ISSUE TITLE
Premailer produces invalid XHTML from valid source

### ISSUE THREAD

**Issue by driekus77** [milkshakesoftware/PreMailer.Net#104] opened 2016-04-16 06:40 UTC
Hi all,

Because of layout problems I've checked my input html against W3C's validator (Both HTML and CSS) and repaired where needed the HTML. Now I have a valid input html but when I run it against PreMailer.NET it becomes invalid. 
My Test doc is XHTML strict (See attached zip)
[drip test.zip](https://github.com/milkshakesoftware/PreMailer.Net/files/222077/drip.test.zip)

The errors I'm getting from W3C's validator is mostly about the end tags not closing. (See beneath for error list).

Premailer.NET works now with most of my tests so it isn't a big issue. But it would be nice if valid (X)HTML is preserved valid.

Thanks and Kind regards,

Henry Roeland

Error list:
Validation Output: 15 Errors

Error Line 1, Column 159: there is no attribute "style"
…="http://www.w3.org/1999/xhtml" style="min-height: 100%;background: #f3f3f3"><…
✉
You have used the attribute named above in your document, but the document type you are using does not support that attribute for this element. This error is often caused by incorrect use of the "Strict" document type with a document that uses frames (e.g. you must use the "Transitional" document type to get the "target" attribute), or by using vendor proprietary extensions such as "marginheight" (this is usually fixed by using CSS to achieve the desired effect instead).

This error may also result if the element itself is not supported in the document type you are using, as an undefined element will have no supported attributes; in this case, see the element-undefined error message for further information.

How to fix: check the spelling and case of the element and attribute, (Remember XHTML is all lower-case) and/or check that they are both allowed in the chosen document type, and/or use CSS instead of this attribute. If you received this error when using the <embed> element to incorporate flash media in a Web page, see the FAQ item on valid flash.

Error Line 2, Column 72: end tag for "meta" omitted, but OMITTAG NO was specified
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
✉
You may have neglected to close an element, or perhaps you meant to "self-close" an element, that is, ending it with "/>" instead of ">".

Info Line 2, Column 5: start tag was here
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
Error Line 3, Column 56: end tag for "meta" omitted, but OMITTAG NO was specified
    <meta name="viewport" content="width=device-width">
✉
You may have neglected to close an element, or perhaps you meant to "self-close" an element, that is, ending it with "/>" instead of ">".

Info Line 3, Column 5: start tag was here
    <meta name="viewport" content="width=device-width">
Error Line 1381, Column 381: end tag for "img" omitted, but OMITTAG NO was specified
…on-mode: bicubic;width: auto;max-width: 100%;clear: both;display: block"> </th>
✉
You may have neglected to close an element, or perhaps you meant to "self-close" an element, that is, ending it with "/>" instead of ">".

Info Line 1381, Column 198: start tag was here
…t;line-height: 19px;font-size: 16px"> <img src="http://placehold.it/150x30/663…
Error Line 1396, Column 322: end tag for "br" omitted, but OMITTAG NO was specified
…serif;font-weight: normal;margin: auto;line-height: 19px;font-size: 16px"> <br>
✉
You may have neglected to close an element, or perhaps you meant to "self-close" an element, that is, ending it with "/>" instead of ">".

Info Line 1396, Column 318: start tag was here
…serif;font-weight: normal;margin: auto;line-height: 19px;font-size: 16px"> <br>
Error Line 1397, Column 265: end tag for "img" omitted, but OMITTAG NO was specified
…0%;clear: both;display: block;margin: auto;float: none;text-align: center"><br>
✉
You may have neglected to close an element, or perhaps you meant to "self-close" an element, that is, ending it with "/>" instead of ">".

Info Line 1397, Column 21: start tag was here
                    <img src="http://placehold.it/120/663399" alt="" class="tex…
Error Line 1397, Column 269: end tag for "br" omitted, but OMITTAG NO was specified
…0%;clear: both;display: block;margin: auto;float: none;text-align: center"><br>
✉
You may have neglected to close an element, or perhaps you meant to "self-close" an element, that is, ending it with "/>" instead of ">".

Info Line 1397, Column 265: start tag was here
…0%;clear: both;display: block;margin: auto;float: none;text-align: center"><br>
Error Line 1415, Column 168: end tag for "hr" omitted, but OMITTAG NO was specified
…border-bottom: 1px solid #cacaca;border-left: 0;margin: 20px auto;clear: both">
✉
You may have neglected to close an element, or perhaps you meant to "self-close" an element, that is, ending it with "/>" instead of ">".

Info Line 1415, Column 21: start tag was here
                    <hr style="max-width: 580px;height: 0;border-right: 0;borde…
Error Line 1452, Column 202: end tag for "br" omitted, but OMITTAG NO was specified
…dding: 0;margin: auto;text-align: left;line-height: 19px;font-size: 16px"> <br>
✉
You may have neglected to close an element, or perhaps you meant to "self-close" an element, that is, ending it with "/>" instead of ">".

Info Line 1452, Column 198: start tag was here
…dding: 0;margin: auto;text-align: left;line-height: 19px;font-size: 16px"> <br>
Error Line 1453, Column 261: end tag for "br" omitted, but OMITTAG NO was specified
…in-bottom: 10px">@copywrite nobody<br> <a href="#" style="color: #2199e8;font-…
✉
You may have neglected to close an element, or perhaps you meant to "self-close" an element, that is, ending it with "/>" instead of ">".

Info Line 1453, Column 257: start tag was here
…margin-bottom: 10px">@copywrite nobody<br> <a href="#" style="color: #2199e8;f…
Error Line 1461, Column 431: end tag for "img" omitted, but OMITTAG NO was specified
…cubic;width: auto;max-width: 100%;clear: both;display: block;border: none"></a>
✉
You may have neglected to close an element, or perhaps you meant to "self-close" an element, that is, ending it with "/>" instead of ">".

Info Line 1461, Column 236: start tag was here
…ne-height: 1.3;text-decoration: none"><img src="http://placehold.it/25/663399"…
Error Line 1464, Column 431: end tag for "img" omitted, but OMITTAG NO was specified
…cubic;width: auto;max-width: 100%;clear: both;display: block;border: none"></a>
✉
You may have neglected to close an element, or perhaps you meant to "self-close" an element, that is, ending it with "/>" instead of ">".

Info Line 1464, Column 236: start tag was here
…ne-height: 1.3;text-decoration: none"><img src="http://placehold.it/25/663399"…
Error Line 1467, Column 431: end tag for "img" omitted, but OMITTAG NO was specified
…cubic;width: auto;max-width: 100%;clear: both;display: block;border: none"></a>
✉
You may have neglected to close an element, or perhaps you meant to "self-close" an element, that is, ending it with "/>" instead of ">".

Info Line 1467, Column 236: start tag was here
…ne-height: 1.3;text-decoration: none"><img src="http://placehold.it/25/663399"…
Error Line 1470, Column 431: end tag for "img" omitted, but OMITTAG NO was specified
…cubic;width: auto;max-width: 100%;clear: both;display: block;border: none"></a>
✉
You may have neglected to close an element, or perhaps you meant to "self-close" an element, that is, ending it with "/>" instead of ">".

Info Line 1470, Column 236: start tag was here
…ne-height: 1.3;text-decoration: none"><img src="http://placehold.it/25/663399"…
Error Line 1473, Column 431: end tag for "img" omitted, but OMITTAG NO was specified
…cubic;width: auto;max-width: 100%;clear: both;display: block;border: none"></a>
✉
You may have neglected to close an element, or perhaps you meant to "self-close" an element, that is, ending it with "/>" instead of ">".

Info Line 1473, Column 236: start tag was here
…ne-height: 1.3;text-decoration: none"><img src="http://placehold.it/25/663399"…

**Comment by martinnormark** [comment] 2016-04-16 21:30
Hey @driekus77 

On a general note, validation HTML for email is really an impossible task. Some email clients are extremely primitive when it comes to HTML, and you often apply hacks and use deprecated tags or attributes to make it work.

For the DOCTYPE, it is actually a bad choice to use the Strict subset of XHTML, as it prevents using many of said tags and attributes for hacks. Campaign Monitor [recommends using `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">`](https://www.campaignmonitor.com/blog/email-marketing/2010/11/correct-doctype-to-use-in-html-email/)

The first validation error, using style attribute on HTML tag, it's only there because a CSS block selects the root HTML tag, so I don't want to overrule what someone is trying to get PreMailer to do - if validation is more important, it is up to the individual developer to remove the CSS block that puts the style attribute there.

As for the omitted trailing slashes of self closing tags, it seems to be by design of AngleSharp - but there's already a PR AngleSharp/AngleSharp/#315 merged to acknowledge trailing slashes and leave them in the HTML. When the `devel` branch over there is merged into `master` and pushed to Nu Get, this should take care of the rest.

**Comment by driekus77** [comment] 2016-04-17 09:48
Hi @martinnormark,

Thanks for your explanation. I will discuss with collega's about which standard to use for email.

Kind regards,
Henry Roeland

**Closed** 2019-09-06 21:15 UTC
